### ISSUE TITLE
HAProxy Vulnerability

### ISSUE THREAD

**Issue by mjrafferty** [iusrepo/haproxy22#13]
Hello,

A colleague of mine showed me this article today:

https://thehackernews.com/2021/09/haproxy-found-vulnerable-to-critical.html

Wanted to point it out in case it wasn't known yet. Any chance on fast tracking the 2.2.17 package to stable repo to address this?

Thanks,
Matt

**Comment by jeffsheltren** [comment]
Thanks @mjrafferty -- I am building the latest version in #14 -- I'll get it pushed to IUS Testing as soon as possible, and would appreciate any testing you or others here are able to do so we can get it pushed to Stable quickly.

**Comment by jeffsheltren** [comment]
2.2.17 is now in IUS stable.
