### ISSUE TITLE
haproxy22 packages for 2.2.21 and/or 2.2.22?

### ISSUE THREAD

**Issue by 9numbernine9** [iusrepo/haproxy22#19]
Greetings!

I noticed that HAProxy `2.2.21` and `2.2.22` have been released over the last couple weeks - are there any plans to build IUS packages for these versions?

Thanks for all your efforts!

**Comment by jeffsheltren** [comment]
haproxy22-2.2.22-1.el7.ius has been pushed to IUS testing
