### ISSUE TITLE
is it possible to setup weekly build to determine haproxy version automatically ?

### ISSUE THREAD

**Issue by chipitsine** [iusrepo/haproxy22#24]
currently haproxy-2.2.26 released, I can write bash script which determines current version and substitute spec appropriately. is it supported by IUS ?

for example, weekly cirrus-ci builds

**Comment by jeffsheltren** [comment]
I don't think we want/need to fully automate builds, but if you can script something to create a PR (or even an issue) on detecting a new release, that may be useful. Unfortunately haproxy doesn't provide an announce-only list so it's hard to stay on top of their releases.

**Comment by chipitsine** [comment]
```
$ curl http://www.haproxy.org/download/2.2/src/releases.json 2>/dev/null| jq .latest_release
"2.2.26"
$
```


I can write custom github action if that is acceptable

**Comment by carlwgeorge** [comment]
The IUS project has reached it's end of life, and will not be addressing any more issues or pull requests.

ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8

iusrepo/announce#41
