### ISSUE TITLE
Timeouts possibly related to protocol upgrade.

### ISSUE THREAD

**Issue by mjrafferty** [iusrepo/haproxy22#5]
I upgraded haproxy to 2.2.9 last night on some servers that were previously using 2.2.3 from a different repo. A client using cloudflare ran into issues this morning with requests timing out that were only fixed by reverting the haproxy version. Here is what I was seeing logged:

``` 
"timers": {
    "request_time": 0,  // %TR
    "srv_connect_time": 1,  // %Tc
    "srv_response_time": 100,  // %Tr
    "total_active_time": 605003,  // %Ta
    "client_estimated_time": 605053  // %Tu
  },
  "termination_state": "sD--"
```

Doing some research this morning, I found this which seems to be extremely similar:

https://www.mail-archive.com/haproxy@formilux.org/msg39765.html

This was corrected in a commit that looks to have come in just a couple days after the last "Latest Upstream" in the rpm changelog:

https://github.com/haproxy/haproxy/commit/a22782b597ee9a3bfecb18a66e29633c8e814216

And here's the info for the rpm we're using if helpful:
```
rpm -qi haproxy22 --changelog
Name        : haproxy22
Version     : 2.2.9
Release     : 2.el7.ius
Architecture: x86_64
Install Date: Thu 25 Feb 2021 12:55:25 AM EST
Group       : Unspecified
Size        : 5989655
License     : GPLv2+
Signature   : RSA/SHA256, Wed 17 Feb 2021 08:59:23 AM EST, Key ID e55807254b274df2
Source RPM  : haproxy22-2.2.9-2.el7.ius.src.rpm
Build Date  : Wed 17 Feb 2021 08:57:40 AM EST
Build Host  : cirrus-ci-task-4669202827051008
Relocations : (not relocatable)
Vendor      : IUS
URL         : http://www.haproxy.org/
Summary     : HAProxy reverse proxy for high availability environments
Description :
HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high
availability environments. Indeed, it can:
 - route HTTP requests depending on statically assigned cookies
 - spread load among several servers while assuring server persistence
   through the use of HTTP cookies
 - switch to backup servers in the event a main one fails
 - accept connections to special ports dedicated to service monitoring
 - stop accepting connections without breaking existing ones
 - add, modify, and delete HTTP headers in both directions
 - block requests matching particular patterns
 - report detailed status to authenticated users from a URI
   intercepted from the application
* Mon Feb 15 2021 Christian Boenning <christian@boenning.io> - 2.2.9-2
- Fix Lua Integration

* Mon Feb 08 2021 Jeff Sheltren <jeff@tag1consulting.com> - 2.2.9-1
- Latest upstream
```

Is there any chance of getting this package rebuilt with that commit above in it so that we can resolve this issue?

Thanks

**Comment by jeffsheltren** [comment]
Hi @mjrafferty thanks for the detailed report! If you -- or whomever -- is able to submit a PR with a patch, I'll consider it. Typically our workflow would be to wait for the next upstream stable release, but I'd be open to a patch since this seems like it may affect a lot of people (anyone behind cloudflare?).

I'll see if I can loop back to this if haproxy doesn't release 2.2.10 soon and nobody else has a PR by then.

**Comment by jeffsheltren** [comment]
haproxy22-2.2.9-3.el7.ius has been pushed to IUS Testing which should fix this issue.

**Comment by mjrafferty** [comment]
Thanks for getting this merged so quickly. Out of curiosity, how long do things stay in ius-testing before moving to ius-stable?

**Comment by hexa2k9** [comment]
@mjrafferty it's outlined in the [Contributing Guide](https://github.com/iusrepo/wishlist/blob/master/.github/contributing.md)

> Do you agree to test the new package to ensure that it works as expected? We don't have any minimum requirements for testing, so use your best judgement and be as thorough as you feel is appropriate. Once you feel the package is ready and would like to see it promoted to the main repository, comment on the issue with the word "STABLE".

That's very likely true for Fixes too I'd assume.

**Comment by jeffsheltren** [comment]
Yeah, if I can get one or two people to comment here that it's working for them, I'll push to stable. Otherwise I generally wait around a week.

**Comment by mjrafferty** [comment]
Sounds good thanks guys.

**Comment by hexa2k9** [comment]
Meanwhile 2.2.10 was released (PR #8) is open for this.

**Comment by jeffsheltren** [comment]
Thanks @hexa2k9 -- seems we can't keep up with haproxy upstream lately! I just merged #8 which includes the upstream fix for this issue. I'll get it pushed to IUS Testing as soon as the build finishes, so please do test there and confirm it fixes this issue.

**Comment by hexa2k9** [comment]
Always thought "IUS" means "inline with upstream" 😉 

I just think official releases are generally a better idea for packages like this rather than "patched versions" while for me the 2.0 Version of HAProxy from IUS is serving several Terrabytes of traffic each day. So thanks for picking up changes so quickly @jeffsheltren & @carlwgeorge. I'll desperately miss IUS for RHEL 8.

**Comment by jeffsheltren** [comment]
Agreed on preferring stable releases. I wasn't sure how long until they'd have one out, so wanted to get a patched version out at least. Thanks again for your PR!

**Comment by carlwgeorge** [comment]
Including a patch is certainly more palatable when it's backported from code already upstream.

**Comment by carlwgeorge** [comment]
haproxy22-2.2.10-1.el7.ius contains this patch and was released to the main repo.
