### ISSUE TITLE
Please build against OpenSSL 1.1 from EPEL7 for TLSv1.3 support

### ISSUE THREAD

**Issue by prupert** [iusrepo/haproxy22#9]
TLSv1.3 support is possible when building HAProxy against OpenSSL 1.1 from EPEL7, which has seen active support for a year now.

[Nginx from EPEL7 has done the same.
](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-c64b965c33)

**Comment by jeffsheltren** [comment]
Added in #10
